//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LandFillNRLEntities : DbContext
    {
        public LandFillNRLEntities()
            : base("name=LandFillNRLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblChangeLog> tblChangeLogs { get; set; }
        public virtual DbSet<tblConsultant> tblConsultants { get; set; }
        public virtual DbSet<tblConsultContact> tblConsultContacts { get; set; }
        public virtual DbSet<tblGeneratorContact> tblGeneratorContacts { get; set; }
        public virtual DbSet<tblGeneratorLocation> tblGeneratorLocations { get; set; }
        public virtual DbSet<tblGenerator> tblGenerators { get; set; }
        public virtual DbSet<tblInterestCharge> tblInterestCharges { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblInvoicee> tblInvoicees { get; set; }
        public virtual DbSet<tblInvoiceesDd> tblInvoiceesDds { get; set; }
        public virtual DbSet<tblInvoicePartialPayment> tblInvoicePartialPayments { get; set; }
        public virtual DbSet<tblLandFillWasteDocket> tblLandFillWasteDockets { get; set; }
        public virtual DbSet<tblLandFillWasteDocketsHistory> tblLandFillWasteDocketsHistories { get; set; }
        public virtual DbSet<tblPaymentMethod> tblPaymentMethods { get; set; }
        public virtual DbSet<tblSubstance> tblSubstances { get; set; }
        public virtual DbSet<tblTruckCompany> tblTruckCompanies { get; set; }
        public virtual DbSet<tblWasteApproval> tblWasteApprovals { get; set; }
        public virtual DbSet<tblWasteDescriptionCode> tblWasteDescriptionCodes { get; set; }
    }
}
