//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConsultant
    {
        public int ConsultantId { get; set; }
        public string ConsultantName { get; set; }
        public string ConsultantAddr { get; set; }
        public string ConsultantCity { get; set; }
        public string ConsultantProv { get; set; }
        public string ConsultantPostal { get; set; }
        public string ConsultantPhone { get; set; }
        public string ConsultantNotes { get; set; }
    }
}
