//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenerator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGenerator()
        {
            this.tblWasteApprovals = new HashSet<tblWasteApproval>();
        }
    
        public int GeneratorId { get; set; }
        public string GeneratorName { get; set; }
        public string GenaratorAddr { get; set; }
        public string GeneratorCity { get; set; }
        public string GeneratorProv { get; set; }
        public string GeneratorPostal { get; set; }
        public string GeneratorPhone { get; set; }
        public string GeneratorComments { get; set; }
        public bool GeneratorExcldInterest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWasteApproval> tblWasteApprovals { get; set; }
    }
}
