//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenerator
    {
        public int GeneratorId { get; set; }
        public string GeneratorName { get; set; }
        public string GenaratorAddr { get; set; }
        public string GeneratorCity { get; set; }
        public string GeneratorProv { get; set; }
        public string GeneratorPostal { get; set; }
        public string GeneratorPhone { get; set; }
        public string GeneratorComments { get; set; }
        public bool GeneratorExcldInterest { get; set; }
    
        public virtual tblWasteApproval tblWasteApproval { get; set; }
    }
}
