//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGeneratorLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGeneratorLocation()
        {
            this.tblWasteApprovals = new HashSet<tblWasteApproval>();
        }
    
        public int GenerLocationId { get; set; }
        public int GenerLocationGenID { get; set; }
        public string GenerLocationLsd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWasteApproval> tblWasteApprovals { get; set; }
    }
}
