//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoicee
    {
        public int InvoiceeID { get; set; }
        public string InvoiceeName { get; set; }
        public string InvoiceeAddr { get; set; }
        public string InvoiceeCity { get; set; }
        public string InvoiceeProv { get; set; }
        public string InvoiceePostal { get; set; }
        public string InvoiceePhone { get; set; }
        public string InvoiceeAttnTo { get; set; }
        public string InvoiceeCareOf { get; set; }
        public Nullable<int> InvoiceeConsultId { get; set; }
    }
}
