//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInvoice()
        {
            this.tblInvoicePartialPayments = new HashSet<tblInvoicePartialPayment>();
        }
    
        public int InvoiceID { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DateInvoiceCreated { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<decimal> VtTotal { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> gstAmount { get; set; }
        public Nullable<decimal> CreditedAmount { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> DateInvoicePaid { get; set; }
        public Nullable<bool> IsManuallyInvoiced { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DatePaymentDue { get; set; }
        public Nullable<int> WasteApprovalId { get; set; }
    
        public virtual tblPaymentMethod tblPaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoicePartialPayment> tblInvoicePartialPayments { get; set; }
    }
}
