//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceesDd
    {
        public int InvoiceeID { get; set; }
        public string InvoiceeName { get; set; }
    }
}
