//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceCreate_Date { get; set; }
        public Nullable<int> ApprovalId { get; set; }
        public Nullable<decimal> VtTotal { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> GstTotal { get; set; }
        public Nullable<bool> PaymentMade { get; set; }
        public Nullable<bool> InvoicePrinted { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<bool> Modified { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string ChequeRefNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<bool> InvoicedManually { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> InterestCharged { get; set; }
    }
}
