//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoicePartialPayment
    {
        public int PartialPaymentId { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<decimal> PartialPayAmount { get; set; }
        public Nullable<System.DateTime> PartialPayDate { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string ReferenceNo { get; set; }
        public string Note { get; set; }
    
        public virtual tblInvoice tblInvoice { get; set; }
    }
}
