//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoicee
    {
        public int InvoiceeId { get; set; }
        public string InvName { get; set; }
        public string InvAddress { get; set; }
        public string InvCity { get; set; }
        public string InvProince { get; set; }
        public string InvPostal { get; set; }
        public string InvPhone { get; set; }
        public Nullable<int> InvContactID { get; set; }
        public string InvAttn { get; set; }
        public string InvCareOf { get; set; }
    }
}
