//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLandFillWasteDocketsHistory
    {
        public int DocketHistoryId { get; set; }
        public int DocketID { get; set; }
        public string DocketNo { get; set; }
        public string WasteApprovalCode { get; set; }
        public Nullable<int> TurckCompanyId { get; set; }
        public string DriverName { get; set; }
        public string DestinatedFor { get; set; }
        public string ScaleTicket { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Tare { get; set; }
        public Nullable<decimal> Net { get; set; }
        public string Cell { get; set; }
        public string Grid { get; set; }
        public string GridNo { get; set; }
        public string Elevation { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> LogEntryTimeStamp { get; set; }
        public Nullable<int> WasteApprovalId { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
    }
}
