//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWasteDescriptionCode
    {
        public int WasteDescriptionId { get; set; }
        public string WasteDescription { get; set; }
        public string WasteDescriptionCode { get; set; }
        public string WasteDescriptionInvoice { get; set; }
    }
}
