//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLandfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWasteApproval
    {
        public int WApApprovalId { get; set; }
        public string WApApprovalcode { get; set; }
        public Nullable<int> WApGeneratorId { get; set; }
        public string WApWasteDescrip { get; set; }
        public Nullable<int> WApSubId { get; set; }
        public Nullable<int> WApLocationId { get; set; }
        public Nullable<System.DateTime> WApCreateDate { get; set; }
        public Nullable<int> WApGenContactId { get; set; }
        public Nullable<System.DateTime> WApExpiryDate { get; set; }
        public Nullable<decimal> WApRate { get; set; }
        public string WApComments { get; set; }
        public Nullable<double> WApExtQuantity { get; set; }
        public Nullable<bool> WApApproved { get; set; }
        public Nullable<bool> WApMailMerge { get; set; }
        public string WApJobNo { get; set; }
        public string WApAfeNo { get; set; }
        public string WApPoNo { get; set; }
        public Nullable<int> WApConsultantId { get; set; }
        public Nullable<int> WApConContactID { get; set; }
        public Nullable<bool> WApAdcApproved { get; set; }
        public Nullable<int> WApInvoicee { get; set; }
        public string WApWasteDescriptionMailMerge { get; set; }
        public Nullable<bool> WApMinCharge { get; set; }
    
        public virtual tblGeneratorLocation tblGeneratorLocation { get; set; }
        public virtual tblGenerator tblGenerator { get; set; }
        public virtual tblSubstance tblSubstance { get; set; }
    }
}
